version: "2"
services:
  psql:
    image: postgres:10.0
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=cachingtest
    volumes:
      - /var/lib/postgresql