#!/bin/bash
# Only run within this directory
# May take some time to run
./googliser.sh "kittens"
./googliser.sh "cats"
./googliser.sh "puppies"
./googliser.sh "dogs"
./googliser.sh "animals"
./googliser.sh "lions"
./googliser.sh "tigers"
./googliser.sh "bears"
./googliser.sh "planet"
./googliser.sh "house"
./googliser.sh "cache"
./googliser.sh "java"
./googliser.sh "coffee"
./googliser.sh "cars"
./googliser.sh "bikes"
./googliser.sh "road"
./googliser.sh "pens"
./googliser.sh "watch"
./googliser.sh "trailer"
./googliser.sh "amazon"
./googliser.sh "physics"
./googliser.sh "psychics"
./googliser.sh "soap"
./googliser.sh "cheese"
./googliser.sh "pear"
./googliser.sh "mango"
./googliser.sh "apple"
./googliser.sh "burger"
./googliser.sh "hat"
./googliser.sh "chair"
./googliser.sh "shoes"
./googliser.sh "jumpers"
./googliser.sh "shirts"
./googliser.sh "bread"
./googliser.sh "country"
./googliser.sh "Ireland"
./googliser.sh "France"
./googliser.sh "England"
./googliser.sh "Scotland"
./googliser.sh "Wales"
./googliser.sh "Germany"
./googliser.sh "Italy"
./googliser.sh "Greece"
./googliser.sh "Russia"
./googliser.sh "China"
./googliser.sh "Japan"
./googliser.sh "Korea"
./googliser.sh "Sweden"
./googliser.sh "Africa"
./googliser.sh "Spain"
./googliser.sh "Poland"
./googliser.sh "Portugal"
./googliser.sh "Belgium"
./googliser.sh "Austria"
./googliser.sh "Norway"
./googliser.sh "Denmark"
./googliser.sh "Iceland"
./googliser.sh "Hungary"
./googliser.sh "Mexico"
./googliser.sh "Brazil"
./googliser.sh "Canada"
python3 removeUnwatedFiles.py "../images"
git clone https://github.com/1carew1/image_uniqueifier
python3 image_uniqueifier/image_uniqueify.py "../images"
python3 reduceDirectorySize.py "../images"