#!/bin/bash
# Only run within this directory
# May take some time to run
./googliser.sh "kittens"
./googliser.sh "cats"
./googliser.sh "puppies"
./googliser.sh "dogs"
./googliser.sh "animals"
./googliser.sh "lions"
./googliser.sh "tigers"
./googliser.sh "planet"
./googliser.sh "house"
./googliser.sh "cache"
./googliser.sh "java"
./googliser.sh "coffee"
./googliser.sh "cars"
./googliser.sh "bikes"
./googliser.sh "road"
./googliser.sh "watch"
./googliser.sh "trailer"
./googliser.sh "amazon"
./googliser.sh "physics"
./googliser.sh "psychics"
./googliser.sh "soap"
./googliser.sh "cheese"
./googliser.sh "pear"
./googliser.sh "mango"
./googliser.sh "apple"
./googliser.sh "burger"
./googliser.sh "hat"
./googliser.sh "shoes"
./googliser.sh "jumpers"
./googliser.sh "shirts"
./googliser.sh "bread"
./googliser.sh "England"
./googliser.sh "Wales"
./googliser.sh "Germany"
python3 removeUnwatedFiles.py "../images"
git clone https://github.com/1carew1/image_uniqueifier
python3 image_uniqueifier/image_uniqueify.py "../images"
# Reduce total image sizes to 2 GB
python3 reduceDirectorySize.py "../images"